# Generated by Django 3.2.18 on 2023-04-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OurTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.TextField()),
                ('ism', models.CharField(max_length=50)),
                ('mansab', models.CharField(max_length=50)),
                ('info', models.TextField()),
            ],
        ),
    ]
