# Generated by Django 3.2.18 on 2023-04-12 16:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.TextField()),
                ('type', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=150)),
                ('sana', models.DateField(default=datetime.date)),
            ],
        ),
    ]
