# Generated by Django 3.2.18 on 2023-04-12 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_news_sana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='sana',
            field=models.DateField(default=datetime.date(2023, 4, 12)),
        ),
    ]
