# Generated by Django 3.2.18 on 2023-04-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20230418_0834'),
    ]

    operations = [
        migrations.CreateModel(
            name='TXabar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xabar', models.TextField()),
            ],
        ),
    ]
